FROM node:8.11.1

LABEL maintainer='klau@bluecedar.com'

RUN apt-get update && apt-get install -y \
    vim

WORKDIR /usr/src/app/

COPY package*.json ./

RUN npm install

COPY ./ ./

EXPOSE 3000

CMD ["npm", "start"]
